# ======================================
# Configurações Customizadas do Keycloak
# ======================================
# Este arquivo contém propriedades específicas do Keycloak
# que não fazem parte das configurações padrão do Spring Security OAuth2

keycloak:
  # Nome do realm no Keycloak
  realm: ${KEYCLOAK_REALM:teste}
  # Client ID da aplicação
  resource: ${KEYCLOAK_CLIENT_ID:cliente-keycloak}
  
 
    
   